--- /usr/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py
+++ /usr/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py
@@ -140,10 +140,6 @@
                 exceptions.HttpError,
                 exceptions.SSLError,
                 exceptions.ConnectionError) as e:
-            LOG.warning('Failed to discover available identity versions when '
-                        'contacting %s. Attempting to parse version from URL.',
-                        self.auth_url)
-
             url_parts = urlparse.urlparse(self.auth_url)
             path = url_parts.path.lower()
 
